### ISSUE TITLE
Memory access violation in TcpClient

### ISSUE THREAD

**Issue by zergler** [kashimAstro/SimpleNetwork#3]
You have a memory access violation on line [69](https://github.com/kashimAstro/SimpleNetwork/blob/d9d192b1d04b46c7463d756f74f853147adf1a3d/src/TCPClient.cpp#L69). Should be `buffer[size - 1] = '\0';` to fix the off-by-one.

**Comment by kashimAstro** [comment]
solved and i add a memset 
to clean the buffer in the receive() method.

thanks
