### ISSUE TITLE
Computer freeze

### ISSUE THREAD

**Issue by sea5kg** [kashimAstro/SimpleNetwork#8]
https://github.com/kashimAstro/SimpleNetwork/blob/3c201857a8214e290f1f1b1acf446eaf623fea3a/example-server/server.cpp#L9

If remove while in loop my computer changed state to freeze and help only reboot

**Comment by kashimAstro** [comment]
Hi @sea-kg, sorry for delay.

now I'm on the travel, as soon as I get back to work, I check this problem.

Ciao
